# Generated by Django 4.2.5 on 2023-09-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0002_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=100),
        ),
    ]
