name: Django Demo

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5  # Choose your Python version

      - name: Install dependencies
        run: |
          pip install -r resturant_web/requirements.txt

      - name: Run Django migrations
        run: |
          cd resturant_web
          python manage.py migrate

      - name: Run tests
        run: |
          cd resturant_web
          python manage.py test
